# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [PBS, USO]
patreon: # Replace with a single Patreon username IHeartRadio
open_collective: # Replace with a single Open Collective username metamask.io
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., tor.onion
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username knightlinelegal
otechie: # Replace with a single Otechie username hunter.ii
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://iab.con','Https://support@marchofdimes.org','Https://Wikipedia.con', 'Https://hunterz.io']
